sudo: true
language: csharp
solution: GameServer.sln
mono: 3.8.0
install:
    - sudo nuget update -self
    - sudo nuget restore GameServer.sln
script:
    - xbuild /p:Configuration=Debug GameServer.sln
notifications:
    email: false